### ISSUE TITLE
Ship wheel on PyPI

### ISSUE THREAD

**Issue by peterbe** [keycdn/python-keycdn-api#11]
At the moment, [only a .tar.gz file is shipped to PyPI](https://pypi.org/project/keycdn/#files).  At least as of version 0.3. 

You just need to install `twine` and then run:

```bash
rm -fr dist/*
python setup.py sdist bdist_wheel
twine upload dist/*
```

**Comment by svenba** [comment]
Release 0.4 is online, thanks!
