### ISSUE TITLE
No tests

### ISSUE THREAD

**Issue by peterbe** [keycdn/python-keycdn-api#17]
I've contributed quite a few things and every time I'm uncomfortable because there are no tests.

**Comment by peterbe** [comment]
Now we're ready to switch on Travis. 

Mind you, in my [PR](https://github.com/keycdn/python-keycdn-api/pull/18) I added a `.travis.yml` file but I realize that not everyone prefers Travis. So let's delete that file if we're not going to use Travis.

**Comment by svenba** [comment]
We don't plan to use Travis for this, thanks.
