### ISSUE TITLE
purge list of files always return "{u'status': u'error', u'description': u'Value is not valid or empty.'}"

### ISSUE THREAD

**Issue by eimsbush** [keycdn/python-keycdn-api#2]
I would like to purge several files from keycdn via 

`        response = api.delete('zones/purgeurl/{}.json'.format(zone_id),
                              params={"urls": cached_thumbnail_names_delete})`

and already tried with

- cached_thumbnail_names_delete as 
-- List of strings: `['/thumbnails/test1.jpg','/thumbnails/test2.jpg']` as 
-- json-string `"['/thumbnails/test1.jpg','/thumbnails/test2.jpg']"`
- also both with zone-domain-prefix:
-- List of strings: `['mycdn1.kxcdn.com/thumbnails/test1.jpg','mycdn1.kxcdn.com/thumbnails/test2.jpg']` as 
-- json-string `"['mycdn1.kxcdn.com/thumbnails/test1.jpg','mycdn1.kxcdn.com/thumbnails/test2.jpg']"`

But the response always contains `"{u'status': u'error', u'description': u'Value is not valid or empty.'}"`

I already tried with differen zones, always with the same response.

**Comment by svenba** [comment]
Please open a support request for this.

**Comment by peterbe** [comment]
For what it's worth, I got that error too, but the change in https://github.com/keycdn/python-keycdn-api/pull/3 solved it and that error went away.
