### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by dmitry-mukhin** [keycdn/python-keycdn-api#20]
Can you add a license to the package?
Thanks!

**Comment by svenba** [comment]
What is the requirement for the license? Why is it needed? Cheers

**Comment by dmitry-mukhin** [comment]
We're using the lib for managing KeyCDN zones and now are doing dependency license audit.
Having no license automatically means a closed license, and this can be difficult to rationalize using the code in a codebase. I know that this is the case for us, and most likely other orgs and users as well.

https://choosealicense.com/no-permission/

**Comment by svenba** [comment]
No problem, just added the license file.

**Comment by dmitry-mukhin** [comment]
thanks!
