### ISSUE TITLE
Import is inconvenient

### ISSUE THREAD

**Issue by peterbe** [keycdn/python-keycdn-api#4]
The README has this example:
```python
import keycdn

api = keycdn.Api('<your_api_key>')
```
that doesn't work because `keycdn` is the package module module. Not the the `keycdn.py` "file module". 

This works though:

```python
from keycdn import keycdn

api = keycdn.Api('<your_api_key>')
```

**Comment by peterbe** [comment]
By the way, if you change the `__init__.py` to `from api import *` and rename `keycdn.py` to `api.py` I think it would work as expected.

**Comment by svenba** [comment]
`import keycdn` should work. I was not able the replicate this.

**Comment by peterbe** [comment]
Confirmed. Not sure what changed or if I had done something differently in the past.

**Comment by peterbe** [comment]
Ah! Must have been https://github.com/keycdn/python-keycdn-api/commit/e3b77c813b3672ea950b3497f8d41c62723cd147

**Comment by svenba** [comment]
Yes, it wasn't fully python3 ready yet.
